### ISSUE TITLE
Subscribe doesn't await the execution results

### ISSUE THREAD

**Issue by dfee** [graphql-python/graphql-core-next#10]
`execute` returns a [`MaybeAwaitable`](https://github.com/graphql-python/graphql-core-next/blob/3de6454304422b3cd832cb1bb075be202e26616c/graphql/execution/execute.py#L115) but `subscribe` doesn't await it if it does.

https://github.com/graphql-python/graphql-core-next/blob/3de6454304422b3cd832cb1bb075be202e26616c/graphql/subscription/subscribe.py#L67-L87

**Comment by dfee** [comment]
I don't know... that doesn't appear to be the problem. Let me give you the symptom:

```python
async def subscribe_count_seconds(
    root: None, info: GraphQLResolveInfo, upTo: int
) -> typing.AsyncIterator[typing.Dict[str, int]]:
    for i in range(upTo):
        yield {"countSeconds": i}
        await asyncio.sleep(1)


async def resolve_count_seconds(  # does not get awaited
    root: None, info: GraphQLResolveInfo, upTo: int
) -> str:
    userid = await authorized_userid(info.context.request)
    return f"you are {userid} and its been {root} seconds"
```

**Comment by Cito** [comment]
Can you post a full test case showing what you do and what you expect to happen?

**Comment by dfee** [comment]
Sure. I created a pretty robust test case that demonstrates how I'd expect it to work. https://gist.github.com/dfee/02264e4e0ea8f6f38ffbeb5e03356473

I have tests for all of it, and it's kinda the basis of some code I'm writing right now.

Anyway, if you look at (and follow) line 371 (`test_subscribe_user`), you can see that the subscription returns a `MapAsyncIterator` instance as expected, and then as that emits, the result is passed to the resolve function (Line 126 / Line 132). Of course, the async resolver doesn't work (which is why I opened this ticket).

**Comment by Cito** [comment]
Sorry for coming back to you only now, @dfee. I like your large test case - can I add it to the test suite?

I've already added a unit test to `test_subscribe` that addresses only your specific issue here, and a small fix that should solve it. Can you confirm that the change above solves your issue?

I also noticed that GraphQL.js has the same issue, so I need confer with them whether this should be backported.

**Comment by dfee** [comment]
@Cito of course you can include it. Also, very interesting regarding GraphQL.js's compatibility. I'll follow up later on whether the patch works.
