### ISSUE TITLE
Middleware defeats introspection without await check

### ISSUE THREAD

**Issue by rob-blackbourn** [graphql-python/graphql-core-next#13]
Fantastic project BTW!

I'm not sure this is a bug, but it caught me out. Maybe it should just be documented.

The following middleware:

    class MyMiddleware:
        async def resolve(self, next, root, info, *args, **kwargs):
            return await next(root, info, *args, **kwargs)

will break the introspection query as the 'next' handler is not awaitable.

This fixes it:

    from inspect import isawaitable
    class MyMiddleware:
        async def resolve(self, next, root, info, *args, **kwargs):
            response = next(root, info, *args, **kwargs)
            return await response if isawaitable(response) else response

Also would it be possible to release 1.0.1 on PyPi as it has all the cool middleware and context stuff :)

**Comment by Cito** [comment]
Thank you. I have mentioned this now explicitly in the docstring of MiddlewareManager.

And yes, 1.0.1 is overdue, it will be published this week.

**Comment by Cito** [comment]
Version 1.0.1 is now available [on PyPI](https://pypi.org/project/GraphQL-core-next/1.0.1/).
