### ISSUE TITLE
Exceptions in resolver are caught (no traceback)

### ISSUE THREAD

**Issue by ceelian** [graphql-python/graphql-core-next#23]
Version:
GraphQL-core-next 1.0.1
Python 3.7.1

**Current Behaviour:**

Exceptions in resolvers are caught by default and the traceback of the original_error doesn't help debugging.

Traceback output of `log.exception('', exc_info=result.errors[0].original_error)`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/execute.py", line 664, in complete_value_catching_error
    return_type, field_nodes, info, path, result
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/execute.py", line 731, in complete_value
    raise result
graphql.error.graphql_error.GraphQLError: My exception
```

**Expected Behaviour:**

1) There is a flag raise_exception which switches if exceptions are caught or if they are raised out of the library resolver. 

2) The traceback of the original_errors is meaningful: leads to the source line where the exception  occurred.

**Comment by Cito** [comment]
@ceelian - thanks for the feedback. Changeset e0bb443 should improve this.

Here is an example how you can get error tracebacks now:

    from traceback import print_tb
    from graphql import *

    def bad_resolver(obj, info):
        raise RuntimeError("the runtime error")

    schema = GraphQLSchema(query=GraphQLObjectType(
        name='RootQueryType',
        fields={'bad': GraphQLField(GraphQLString, resolve=bad_resolver)}))

    error = graphql_sync(schema, '{ bad }').errors[0]
    original_error = error.original_error

    print(error)
    print_tb(error.__traceback__)

Output:

    the runtime error

    GraphQL request (1:3)
    1: { bad }
         ^

      File ".../execute.py", line 664, in complete_value_catching_error
        return_type, field_nodes, info, path, result
      File ".../execute.py", line 731, in complete_value
        raise result
      File "../\execute.py", line 619, in resolve_field_value_or_error
        result = resolve_fn(source, info, **args)
      File "test_graphql.py", line 7, in bad_resolver
        raise RuntimeError("the runtime error")

Will release an upate with this improvement soon.

**Comment by ceelian** [comment]
Great, thank you for the improvement!

**Comment by ezyang** [comment]
Thank you, I was affected by this too.

**Comment by Cito** [comment]
Version [1.0,2](https://pypi.org/project/GraphQL-core-next/1.0.2/) with this fix has now been released on PyPI.
