### ISSUE TITLE
Document difference from graphql-js

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql-python/graphql-core-next#24]
@Cito You doing a great job keeping this lib in sync with `graphql-js`.
Also big thanks for taking the time to submit PRs back to `graphql-js` 👍 

I was browsing the source code and notice that you already implemented `middlewares`:
https://github.com/graphql-python/graphql-core-next/blob/master/graphql/execution/middleware.py

Would be great to have a list of such changes so we can figure out is it something Python specific or we should push it into `graphql-js`.

I also interested if you added any new tests that we can mirror in `graphql-js`.

**Comment by Cito** [comment]
I was actually lagging behind and trying to catch up this weekend again. Still missing the last two months of changes...

My intention for graphql-core-next was to avoid differences and additions and keep everything as close to GraphQL.js as possible. Currently there are only two additions which have been taken over from the older graphql-core for backward compatibility reasons: support for [middleware](https://github.com/graphql-python/graphql-core-next/pull/7) and a [custom execution context](https://github.com/graphql-python/graphql-core-next/pull/6). You're right, these should be mentioned particularly in the docs. I'll keep this open as a reminder.

I also try to keep the test suite in sync and send PRs when I notice problems or make additions. One user contributed a [test_user_registry](https://github.com/graphql-python/graphql-core-next/blob/master/tests/test_user_registry.py) test/demo covering mutations and subscriptions, which I have added as a top level test to the test suite, similar to the star wars test/demo.

**Comment by IvanGoncharov** [comment]
@Cito Thanks for the details.

I think we need to have middlewares in `graphql-js` but at the moment I've focused more on paying the technical debt for features we already have, e.g. `buildSchema`/`extendSchema`.

BTW. I notice you don't use `contain_subset` anymore so it looks like you can safely delete it:
https://github.com/graphql-python/graphql-core-next/search?q=contain_subset&unscoped_q=contain_subset

**Comment by Cito** [comment]
@IvanGoncharov  Right, `contain_subset` is not needed any more after graphql/graphql-js/commit@1d07ebfc10773c431e4d9ae9c35bc11f8d940c01 - removed it now.

**Comment by Cito** [comment]
Note to self: Document #41, #42 and overridable `type_map_reducer`.

**Comment by IvanGoncharov** [comment]
@Cito A little bit off-topic but why do you need overridable `type_map_reducer`?

**Comment by Cito** [comment]
@IvanGoncharov This is to support [Graphene](https://graphene-python.org/), a higher-level and more Pythonic library wrapping GraphQL-core. Graphene uses a custom reducer to convert its own types to the GraphQL-core types.

**Comment by Cito** [comment]
The [documentation](https://graphql-core-next.readthedocs.io/en/latest/diffs.html) has been added now in 2999def3f23d024128d042c0cf539a825fb00a20.
