### ISSUE TITLE
mypy seemingly can't find types for this package

### ISSUE THREAD

**Issue by ezyang** [graphql-python/graphql-core-next#26]
When I attempt to run mypy, I get:

```
ghstack/github_fake.py:1: error: Cannot find module named 'graphql'
ghstack/github_fake.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```

Now, I know that you guys have types... but the mypy docs seem to suggest that you need to do something extra to get mypy to treat the third party package as having types?

As a temporary workaround, I've symlinked `graphql` in my local directory to graphql-core-next/graphql and that convinces mypy to check the ytpes.

**Comment by Cito** [comment]
How exactly did you call mypy? Note that the mypy command line tool exepects a module file or folder name on the file system, not the name of an installed package.

**Comment by ezyang** [comment]
I just did `mypy my_module.py`, where `my_module` imports GraphQL-core-next

I believe the problem is that you need a py.typed file in your package directory. See https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages

**Comment by Cito** [comment]
Oh, ok, now I understand. Yes, I believe you're right, there should be such an (empty) file as a marker. Will add this to the next version. Need to rethink the packaging anyway (#22).

Thanks a lot for pointing this out!

**Comment by Cito** [comment]
Version 1.0.3 with this fix is now available.
