### ISSUE TITLE
Provide graphql-tools functionality in Python

### ISSUE THREAD

**Issue by Cito** [graphql-python/graphql-core-next#27]
Creating executable schemas from SDL with GraphQL.js/graphql-core-next is possible, but grafting resolvers, custom scalars and enums manually into the schema after creating it with `build_schema` is cumbersome (see e.g. #20) and has a smell of monkey-patching.

The `makeExecutableSchema` function of [graphql-tools](https://www.apollographql.com/docs/graphql-tools/) provides a better solution.

We should consider porting this functionality to Python as well, either as a separate packare or as a subpackage of graphql-core-next.

**Comment by patrys** [comment]
You might want to take a look at https://github.com/mirumee/ariadne 😄

**Comment by Cito** [comment]
@patrys - thanks, wasn't aware that this existed. Nice! Will definitely look into that. Maybe it will suffice mentioning this in the documentation.

**Comment by Cito** [comment]
I have mentioned Ariadne now in the README.

**Comment by jberryman** [comment]
FWIW I arrived here because I was looking for functionality that could "prune" a schema by removing unreachable types, similar to what's offered in graphql-tools
