### ISSUE TITLE
Roadmap/Status update?

### ISSUE THREAD

**Issue by changeling** [graphql-python/graphql-core-next#29]
What's the status of graphql-core-next vis-a-vis the graphene tools? Is there a Roadmap or other document tracking compatibility with, say, graphene-django?

Or are they already compatible and I'm missing that in the docs of those tools or graphql-core-next?

It would be great if this was addressed prominently in the README. Assuming it isn't already and I'm just flat out missing it.

**Comment by Cito** [comment]
Currently the tools are only compatible with graphql-core. But we are planning to base the next major version of Graphene and other tools on core-next. See also graphql-python/graphene#954.

I'm planning to push a new release with updated README this week, but currently some things are still under discussion - e.g. whether core-next should be released as core 3.

**Comment by changeling** [comment]
Thanks for this!

I have been (trying) to follow the relevant conversations here, including https://github.com/graphql-python/graphene/issues/884 and https://github.com/graphql-python/graphql-core/issues/241, but it has required some detective work digging through the issues to find them, and brings with it the confusion of trying to figure out which thread is canonical, which are out-dated and what information regarding the different integrations, the core and graphene is both current and useful.

Your updated README will be welcome! :)

I think, going forward, addressing such issues for and from the user perspective, or rather, up front in README/ROADMAP/etcetera rather than threaded amongst the Issues will help a lot with adoption, and absolutely resolving the versioning/naming issues in itself will be a great step forward.

Thank you, and all involved, for stepping up to keep this ecosystem alive.

**Comment by Cito** [comment]
Ok, I have added a section to the README now.
