### ISSUE TITLE
Implementing logic for a custom Directive - SchemaDirectiveVisitor?

### ISSUE THREAD

**Issue by dvndrsn** [graphql-python/graphql-core-next#33]
Is there anything in `graphql-core-next` like the schema directive visitor pattern mentioned in the `graphql-tools` documentation? How does one implement custom logic for a Directive?

Apollo docs:
https://www.apollographql.com/docs/graphql-tools/schema-directives#implementing-schema-directives

Code in question:
https://github.com/apollographql/graphql-tools/blob/wip-schema-directives/src/schemaVisitor.ts#L459

**Comment by Cito** [comment]
No, graphql-tools is outside the scope - the goal of graphql-core-next is to replicate GraphQL.js only.

Someone would need to create something like graphql-tools or [graphql-directive](https://github.com/smooth-code/graphql-directive) for Python.

**Comment by dvndrsn** [comment]
Thanks for clarifying!
