### ISSUE TITLE
Trailing comments in query causes "string index out of range"

### ISSUE THREAD

**Issue by andrewspode** [graphql-python/graphql-core-next#39]
I'm using graphiQL for testing my API where it is fairly common practice to comment out a query and write a new one.

```
{info}
```

Will run fine.

```
{info}
#
```

Will fail with "string index out of range" on line 268 of lexer.py (char=body[position])

I could be wrong - but shouldn't that be a >= rather than >?

**Comment by Cito** [comment]
Thank you for the bug report, @andrewspode . You are right, that should be a `>=`.
