### ISSUE TITLE
Support "out_name" in input types

### ISSUE THREAD

**Issue by Cito** [graphql-python/graphql-core-next#41]
GraphQL-Core supports an `out_name` for input types which is used by Graphene for passing parameters with transformed names to Python (because Python likes snake_case instead of camelCase).

GraphQL-Core-Next should support a similar functionality that can be used by Graphene.

**Comment by Cito** [comment]
This is now fully supported and works the same as in GraphQL-core.

**Comment by Hellzed** [comment]
Is there a way to use this feature with an SDL-first approach?
I'm using `build_schema` to get my schema from the SDL, in addition with resolver methods on my `root_value`, and I would prefer my resolvers to get snake case instead of camel case.

**Comment by Cito** [comment]
You will need to patch the schema setting the out_names to the input fields. Something like this will probably do:
```python
from graphql.pyutils import camel_to_snake

for field_name, field in schema.query_type.fields.items():
    for arg_name, arg in field.args.items():
        arg.out_name = camel_to_snake(arg_name)
```

**Comment by Hellzed** [comment]
Thanks for the tip, I'll try this ASAP!
