### ISSUE TITLE
Scalar variables failing validation

### ISSUE THREAD

**Issue by astronouth7303** [graphql-python/graphql-core-next#51]
When I validate [these queries](https://github.com/go-build-it/gqlmod/blob/master/testmod/queries.gql) against [this schema](https://github.com/go-build-it/gqlmod/blob/master/gqlmod_starwars/schema.py) (via [this code](https://github.com/go-build-it/gqlmod/blob/6fe690f7ffb0634f4522ded57be8f40b21205c52/gqlmod/importer.py#L94-L103)), I'm getting this error:

```
graphql.error.graphql_error.GraphQLError: Unknown type 'Int'.

/home/astraluma/code/gobuildit/gqlmod/testmod/queries.gql:15:30
14 | 
15 | query HeroComparison($first: Int = 3) {
   |                              ^
16 |   leftComparison: hero(episode: EMPIRE) {
```

The results of `pip freeze`:

```
astor==0.8.0
-e git+git@github.com:go-build-it/gqlmod.git@6fe690f7ffb0634f4522ded57be8f40b21205c52#egg=gqlmod
graphql-core==3.0.0a2
import-x==0.1.0
pkg-resources==0.0.0
```

I'm pretty new to GraphQL, but as I understand it, `Int` is a builtin scalar that should always be available?

**Comment by Cito** [comment]
Hi @astronouth7303. Graphql-core is replicating the behavior of graphql-js. Whether built-in scalars are added automatically or not has changed in the last versions of graphql-js (see graphql/graphql-js/issues/2005). The current state is that they are *not* added automatically, i.e. they are only included if they are used in the schema (which makes sense, if you think about it).

The actual problem here is that the query type for friendsConnection used in your query is not part of the schema, so it would not validate against that schema anyway. You need to add that type to your schema first. To construct such connection types, you can use [graphql-relay-py](https://github.com/graphql-python/graphql-relay-py).

**Comment by astronouth7303** [comment]
Yeah, I pulled the queries from the graphql tutorial but the schema from this project's test suite. I guess they mismatch more than I think. (The starwars code is mostly for testing and toying.)

> (which makes sense, if you think about it)

Ummm... I suppose? Most type systems I work with assume some number of universal builtins.

It's not clear to me what problems "automatically add builtin scalar types" creates, and that's some pretty dense stuff to wade through. I'll try again later.

* Is this error message a sign that this query will never validate? (Can it maybe be improved in the case of builtin names?)
* Am I missing an invocation/argument to add the builtin types on either the client and/or server side?

**Comment by Cito** [comment]
Yes, this query will never validate or execute until you add the friendsConnection type to your schema. And when you do this, it will then also include the Int type automatically, because it is used by the friendsConnection. You don't need to add the builtin-types manually.

**Comment by astronouth7303** [comment]
I think I might do that anyway, just for UX reasons. 

* "Int not defined" => "wtf, is this thing bugged?"
* "friendsConnection isn't found on Character" => "Oh, that's not in this schema"

Like, yeah, the query will fail to validate either way, but the first one is weird and confusing and makes you question life, while the second is sensible and useful.

**Comment by Cito** [comment]
GraphQL is nice in that regard: ExecutionResult.erros is a *list* of errors, you will get one error for the missing Int and another one for the missing friendsConnection. The missing Int error only comes first because it appears first (in line 1), while the other one appears later (in line 12).

**Comment by astronouth7303** [comment]
In my application, I have to pick one error and raise that, and the error that appears first in the file is the obvious one.

(Yes, I'll add a CLI tool later that'll show all errors, but MVPs and all that.)
