### ISSUE TITLE
ETA for 3.0.0 release

### ISSUE THREAD

**Issue by pmantica1** [graphql-python/graphql-core-next#53]
Thank you for the hard work porting the reference GraphQL implementation to python3. We are hoping to start using this library once the stable 3.0.0 version is released. Do you have a rough idea of when this will be?

**Comment by Cito** [comment]
There will be a beta version this month and the final next month, maybe a bit earlier. Don't hesitate to use the library already. The alpha label is a bit misleading - the API is stable since it replicates GraphQL.js, we just didnt't want to break tools requiring graphql-core which are not compatible yet with version 3. We're also interested in getting feedback that can be used for the final release.

We can leave this issue open until 3.0 final has been published.

**Comment by Cito** [comment]
[Version 3.0.0b0](https://github.com/graphql-python/graphql-core-next/releases/tag/v3.0.0b0) has been released now. The 3.0.0 final version will be released soon, depending on feedback to the beta version.

**Comment by robjampar** [comment]
any updates on this? the beta version is working great for me, we want to do a release of one of our libraries but were waiting for 3.0.0 to ship!

**Comment by Cito** [comment]
I'm aiming at mid of November for the final release.

**Comment by obi1kenobi** [comment]
If there is a burndown list of issues that need to be tackled for the 3.0 release, I'd be happy to pitch in and help. If we can get 3.0 out by the end of the month, that would unblock fixes for a ton of issues (some of which point to this thread) and I'd be happy to help in any way I can.

Given the stability of the beta, I'd honestly also be okay with tagging and releasing it as the proper 3.0 release if that's easier. I haven't found any issues with the beta so far and it seems at least one other commenter feels the same way. I just want to be able to install the package without the `--pre` flag 😄

**Comment by Cito** [comment]
Ok, if that helps, I will try to release 3.0 end of this week, probably will have some time on Nov 30 or Dec 1.

**Comment by obi1kenobi** [comment]
That's awesome, thank you so much! Please feel free to @ me if there's anything I can do to help.

**Comment by Cito** [comment]
[Version 3.0.0](https://github.com/graphql-python/graphql-core-next/releases/tag/v3.0.0) has been released now.
