### ISSUE TITLE
Rules for directive's arguments not executed if no args declared on directive

### ISSUE THREAD

**Issue by Dodobibi** [graphql-python/graphql-core-next#63]
If a directive with no argument declared and an arbitrary argument is passed, the rule check is not applied.

This is because `know_args` is an empty list  which return _false_ in `if directive_node.arguments and known_args:` at [Line 63 on /src/graphql/validation/rules/known_argument_names.py](https://github.com/graphql-python/graphql-core-next/blob/master/src/graphql/validation/rules/known_argument_names.py#L63)

**Comment by Cito** [comment]
Thank you @Dodobibi for reporting this and pinpointing the problematic code. 👍
