### ISSUE TITLE
Question: how to perform an operation before the futures will be resolved

### ISSUE THREAD

**Issue by maartenbreddels** [graphql-python/graphql-core-next#64]
Hi,

awesome project, going Python 3.6+ and full async is a really big improvement!

For context: I'm creating a GraphQL binding to [Vaex](https://github.com/vaexio/vaex/), a Python DataFrame library for large datasets, mostly exposing the aggregations and groupby/binby operations. The aggregation operations can be done async (they will give a Promise, that I can wrap with a Future for compatibility with this library). All operations will then be performed in one pass over the data, and thus all promises/futures will be resolved after that operation. This 'one pass over the data' is required for proper performance for larger than memory datasets.

I thus need to call vaex to compute the aggregation before your library tries to resolve the futures, but after all graph-ql operations are executed. In the previous version of this library, I could do this by calling my computation function in https://github.com/graphql-python/graphql-core/blob/bbbe880673e2574bc418b639f43968f96364873b/graphql/execution/executors/asyncio.py#L55 (by inherting and overriding that method).

However, I cannot find an easy way to do this with the current library. The only way I could do it was to pass my function as the context, and call it just before this line : https://github.com/graphql-python/graphql-core-next/blob/0fb5b81fc0a1909bfe63df31657bc4de631676cf/src/graphql/execution/execute.py#L356

Is there a proper way of achieving this?

cheers,

Maarten

**Comment by Cito** [comment]
Maybe you can make use of a middleware or a custom execution context class? You can pass both to the graphql() function. Have a look at tests/execution/test_middleware.py for how to use middleware.

**Comment by maartenbreddels** [comment]
I think I can solve it with the execution context, thanks!
For the moment I'm sticking to the 'old' version of the library, but I'll use that solution in the future.
