### ISSUE TITLE
Premature removal of introspection_query

### ISSUE THREAD

**Issue by Cito** [graphql-python/graphql-core-next#69]
In GraphQL-core 3.0.0, `introspection_query` has been already removed, although 3.0.0 claims to be compatible with GraphQL.js 14. This should only be removed when we release a version compatible with GraphQL.js 15.

**Comment by djstein** [comment]
can confirm this is a breaking change.

**Comment by Cito** [comment]
Will release a bugfix soon. The recommended usage that should work with all versions is `from graphql.utilities import get_introspection_query` or `from graphql import get_introspection_query` and then `introspection_query = get_introspection_query()`. You can also pass whether you want descriptions as an argument.

**Comment by Cito** [comment]
This has now been fixed in version 3.0.1.
