### ISSUE TITLE
Exception instance returned from resolver is raised within executor instead of being passed down for further resolution.

### ISSUE THREAD

**Issue by rafalp** [graphql-python/graphql-core-next#72]
Today when experimenting with 3rd party library for data validation (https://github.com/samuelcolvin/pydantic) I've noticed that when I take map of validation errors from it (which is dict of lists of `ValueError` and `TypeError` subclasses instances), I need to implement extra step to convert those errors to something else because query executor includes check for `isinstance(result, Exception)`. This check makes it raise returned exception instance, effectively  short-circuiting further resolution:

https://github.com/graphql-python/graphql-core-next/blob/master/src/graphql/execution/execute.py#L731

The fix for issue was considerably simple to come up with: just write util that converts those errors to a dict as they are included in my result's `validation_errors` key, but I feel such boilerplate should be unnecessary:

```
try:
    ... run pydantic validation here
except (PydanticTypeError, PydanticValueError) as error:
    return {"validation_errors": flatten_validation_error(error)}
```

Is this implementation a result of something in spec, or mechanism used to keep other feature's (eg. error propagation) code simple? I think we should consider supporting this use-case. Considerable number of libraries use exceptions for messaging (eg. Django with its `ValidationError` and bunch of `core.exceptions.*`)

**Comment by Cito** [comment]
This is exactly what GraphQL.js does as well:

https://github.com/graphql/graphql-js/blob/fbed2c2356eeb83d84280ae3c0635eb54e04a419/src/execution/execute.js#L809

However, the raised error is always caught and wrapped into a located error in the `complete_value_catching_error` method.
