### ISSUE TITLE
Unclear how to distinguish between "intentional" and "server error" exception cases

### ISSUE THREAD

**Issue by akdor1154** [graphql-python/graphql-core-next#79]
Heya,
I'm writing a server with the error philosophy that
 - if a resolver wants to return an "errors: {blah}" object to the client, I will handle this case explicitly (by some arbitrary method, e.g. raising a special Exception class, returning a special Error() result, etc)
 - any other exception in my server is "unexpected", and should be treated as a server error and result in a 500.

This is analogous to the pattern of Result (Ok, Error) in many functional languages. Result.Error is returned for an "expected" error, and potentially manually displayed to the client; any exceptions are "unexpected" and are truly exceptions in the sense that they define unexpected behaviour from my server and should hence not be exposed to clients.

It's unclear how I can achieve this with the error model of graphql-core-next. Some GraphQL errors are clearly of the second type (e.g. I've defined my schema incorrectly, `GraphQLError('Type UnknownTransactionReturn must define one or more fields.')`), but as far as I can tell, this library doesn't give me the ability to distinguish those from the first type (e.g. the user submitted a malformed graphql query).

Currently I am trying to achieve this by inspecting `.errors` in my `ExecutionResult`s. (checking for original_error to see where GraphQL is hiding exceptions, etc.)

Is there any way to achieve the control over error behaviour that I am seeking here?

**Comment by Cito** [comment]
As you already found out, you can check the `original_error` to see which error has been raised.

You can also raise GraphQLErrors like this:
```python
raise GraphQLError("This is a custom error", extensions={'custom': True})
```
The extensions are then available in the formatted result on the client. You can also process GraphQL errors and convert errors found in `original_error` to additional info passed in `extensions`.

Note that this library simply mirrors what GraphQL.js is doing, which follows the GraphQL specs. This includes handling of errors in GraphQL.js. Additional error processing. enriching the error output or filtering it, depending on whether you run in producion or development, can happen on top of that.

**Comment by kaos** [comment]
I found this snippet very helpful. Maybe include an example based on that in the documentation?
https://github.com/graphql-python/graphql-server/issues/10#issuecomment-382809784
EDIT: updated the above snippet to work with graphql-core v3: https://github.com/graphql-python/graphql-server/issues/10#issuecomment-725980428
